FROM node:18-alpine

WORKDIR /app
ENV NEXT_PUBLIC_DOMAIN http://pushkamusic.online
COPY package*.json ./

RUN npm install

COPY . .

ENV NODE_ENV production
RUN npm run build
RUN npm prune --production
CMD ["npm", "start"]
