import { Sidebar } from "./components"
import styles from "./layout.module.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body>
        <div className={styles.container}>
        <Sidebar />
        <div className={styles.content}>
          {children}
        </div>
        </div>
        
      </body>
    </html>
  )
}
