import { Sidebar } from "./components"
import styles from "./layout.module.css"
import '../styles/global.css';
import localFont from "next/font/local";
import '../styles/global.css';

const sfProDisplay = localFont({
  src: [
    {
      path: '../../public/fonts/SFProDisplay-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/SFProDisplay-RegularItalic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../../public/fonts/SFProDisplay-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/SFProDisplay-BoldItalic.ttf',
      weight: '700',
      style: 'italic',
    },
    {
      path: '../../public/fonts/SFProDisplay-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/SFProDisplay-LightItalic.ttf',
      weight: '300',
      style: 'italic',
    },

  ],
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={sfProDisplay.className}>
        <div className={styles.container}>
        <Sidebar />
        <div className={styles.content}>
          {children}
        </div>
        </div>
        
      </body>
    </html>
  )
}
