FROM node:18-alpine

# Установка NestJS CLI глобально
RUN npm install -g @nestjs/cli


# Установка рабочего каталога для приложения
WORKDIR /opt/app

# Копирование package.json и package-lock.json (если доступно)
ADD package.json package.json

# Установка зависимостей
RUN npm install 

# Копирование остальных файлов проекта
COPY . .

# Сборка приложения
RUN npm run build


# Определение команды для запуска приложения
CMD ["npm", "run", "start:dev"]
